[writing]
name = "writing"
author = "Cerabbite"
version = "0.2.0pa-nightly-UNIX"
update_type = "nightly" # standard: quarter | options: alpha (0.0.0a or 0.0.0b), nightly (0.0.0-nightly), full (x.0.0), half (0.x.0), quarter (0.0.x), all (x.x.xa-nightly)
auto_update = false # standard: false | options: true, false
release_date = "xx/xx/2022"
