[package]
name = "writing"
version = "0.2.0"
edition = "2021"
author = "Cerabbite"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12.0"
chrono = "0.4"
