[writing]
name = "writing"
version ="0.2.0"
license = "MIT-License"
authors = ["Cerabbite"]
description = ""
homepage = ""
repository = "https://github.com/Cerabbite/writing"

[general]
font-color = "white"

[errors]
error-report = "simple"
error-color = "red"

[fountain]

[novel]